### ISSUE TITLE
How to find libc file

### ISSUE THREAD

**Issue by InersIn** [dosxuz/DownUnderCTF#1]
Can you explain how to find libc file? please

**Comment by dosxuz** [comment]
Yeah sure! What I did was I just copied the leaked puts address and pasted it onto the online libc database https://libc.blukat.me/
I copied the address on the right block and wrote puts on the left block. You'll find two libc version, one of them will be for amd64. That's the one you need. You can also use the offline libc database which you can get from their GitHub. I'll edit the writeup shortly, describing the libc stuff.

**Comment by InersIn** [comment]
ok thank you, appreciate it

**Comment by dosxuz** [comment]
Details on finding remote libc has been added
